sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.0
before_install: gem install bundler -v 1.17.1
deploy:
  provider: rubygems
  api_key:
    secure: t7jNoz9Ct19jfGikW2lxK39aNPbvbFTwkhvVQ4ZlSAn+0iUWSmcTDFnh6MiSJFi9PEGvH3AUIrs6s7p6vhWUB8ll3S1UpC+34izUQZjUUHssJ+tf+A9q27OtX/O9PUsoOkHiq8/3F8SRT1OqyKb9+DR6i/M9MpHgWKLVEmXq3MXnGin1TeNJ70Hy2hakwbH/LdprrfT0LUohLZYzVFEodBPXRWeplJSAnJlyTrSIfIZV9e716L0F3HbXYY6pE5PJkFUSWwzAyO0Z73PJVV5+VsHt10AbHIJzPqf/qsLtC4K4SICWO7Xtnyuu9erg0HjG+y2D3AHbMklP/vJk4y1J2m6aJEzJ4VUVYfbVbkomPV0ol6alPmd6rCth8FQSZ5IFulwfp3qcsvSxS1BDhKl1yDC1di6n5MH9YNndy6puy6VTuuz4lqCya4WA1aBeummb9WsH2CNIws+rLneoH7PsMz6DCx9YhxbfZkh8h0WXRUgl86Ir1RbKbhR4+b3P1MFart55ipJ/tWMtyWOdJvjgakEyR/QMUEkWFMCOHuQd+Iv3PGT5God9YV6L01X/26BIfiHcTZTi2f5RDSyy6vIaOMROLKKU+heK3CGWvemA24uuJbyH9b3QujypCrR7wLRYvfGHeHunFbFH4HHZj+aedvtxzyJ004kNsia2y1TSw6c=
  gem: eight_ball
  on:
    tags: true
    repo: rewindio/eight_ball
