sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.0
before_install: gem install bundler -v 1.17.1
deploy:
  provider: rubygems
  api_key:
    secure: A+rr3FbuuaaGpofaU2ITYDp4THKXAgJJDPKiZgCFEji3i4LQ4pNVDWEpsKcNCY8q+EnOyUNR01v8+cXGvgblCQv+uJ2VRJdw0llbTfTOml0lLtLDf6wpNqdlPYtUFrRfa6NbGdkd3J9cVkBVA89rjiMT9DUsb/VeMnO4vvgWi9KMAprQrx2XOTUmkYiwO7KdHtVou42HVpJy51aGkyYdZfW/L+g6F7AFZ6KD4E6nwu7ZUd84SPj1gXq746BoAa/xDY6s6/YBIxdQnO8WLjCbIdhU3kt0T1MXo26cx4K8YNLsS/vQE6enkTScPQnaTo71IwRW6i8daoHNmF2IP7RUXvZk8D8XYm5CHSgo97GWropcEqq1QtttviwSTH/05nkiE2FfsRYx+4lrzvjofL1+8BmSavJepw7dpIO6rJUM6tMPKVjKQOpMZ26BRi0d9wusnh2XuRM6bCiDD8oiJL7o9WtPHev87p7NlvEJDgoAKYw21YDTBLldsBbz08TbF0wkrhyyu8FbUSO0jSnWXILe5PWl/19QSp5ryzRxgPFSOWuUKfSLSyOVLg1brFprM/fG5e+46oBmD3LDLtQSWttPfHb6NGV1Dw3eoGjj8kp7FS+tK5IYiSmBbrYFUZngw39m2FGa1H4oXDsuebd6VkukVJwAIMpwyvPXC2yvKKpgmHQ=
  gem: eight_ball
  on:
    tags: true
    repo: rewindio/eight_ball
