name: tag-and-release

on:
  push:
    branches:
      - main
    paths:
      - 'lib/*/version.rb'

jobs:
  release:
    uses: rewindio/github-action-common/.github/workflows/tag-and-release.yml@v1
    with:
      registry: github
      ruby_version: 2.7
    secrets:
      REGISTRY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
